unsigned char WholeCube(unsigned char a);
void _setWholeCube(void);
void _clearWholeCube(void);
void _invertWholeCube(void);
unsigned char Layer(unsigned char layer, unsigned char a);
void _setLayer(unsigned char layer);
void _clearLayer(unsigned char layer);
void _invertLayer(unsigned char layer);
unsigned char Pixel(unsigned char x, unsigned char y, unsigned char z, unsigned char a);
void _setPixel(unsigned char x, unsigned char y, unsigned char z);
void _clearPixel(unsigned char x, unsigned char y, unsigned char z);
void _invertPixel(unsigned char x, unsigned char y, unsigned char z);
unsigned char Cube(unsigned char x1, unsigned char y1, unsigned char z1, unsigned char x2, unsigned char y2, unsigned char z2, unsigned char a);
unsigned char FilledCube(unsigned char x1, unsigned char y1, unsigned char z1, unsigned char x2, unsigned char y2, unsigned char z2, unsigned char a);
void _setFilledCube(unsigned char x1, unsigned char y1, unsigned char z1, unsigned char x2, unsigned char y2, unsigned char z2);
void _clearFilledCube(unsigned char x1, unsigned char y1, unsigned char z1, unsigned char x2, unsigned char y2, unsigned char z2);
void _invertFilledCube(unsigned char x1, unsigned char y1, unsigned char z1, unsigned char x2, unsigned char y2, unsigned char z2);
unsigned char EdgeCube(unsigned char x1, unsigned char y1, unsigned char z1, unsigned char x2, unsigned char y2, unsigned char z2, unsigned char a);
unsigned char Line(unsigned char x1, unsigned char y1, unsigned char z1, const unsigned char x2, const unsigned char y2, const unsigned char z2, unsigned char a);